### ISSUE TITLE
build image from Dockerfile failed: When using COPY with more than one source file, the destination must be a directory and end with a /

### ISSUE THREAD

**Issue by ooooona** [SeldonIO/MLServer#1045] opened 2023-03-15 14:41 UTC
Hi, I'm trying to build MLServer Image from the [Dockerfile](https://github.com/SeldonIO/MLServer/blob/master/Dockerfile) but failed with the error message:
```bash
docker build -t mlserver-oona-test:1.0.0 .
Sending build context to Docker daemon  8.063MB
Step 1/26 : FROM python:3.8-slim AS wheel-builder
 ---> 12d27a707dfd
Step 2/26 : SHELL ["/bin/bash", "-l", "-c"]
 ---> Running in 70c5153c4990
Removing intermediate container 70c5153c4990
 ---> 6559823e579c
Step 3/26 : COPY ./hack/build-wheels.sh ./hack/build-wheels.sh
 ---> 877b58ef22fb
Step 4/26 : COPY ./mlserver ./mlserver
 ---> e80a3288b0e6
Step 5/26 : COPY ./runtimes ./runtimes
 ---> 56954fde332a
Step 6/26 : COPY     setup.py     README.md     .
When using COPY with more than one source file, the destination must be a directory and end with a /
```

It worked after I modified the [code of Dockerfile](https://github.com/SeldonIO/MLServer/blob/master/Dockerfile#L7-L10) as bellow:
```
COPY \
    setup.py \
    README.md \
    ./
```

Then I wonder if it is really a bug or something wrong with my environment? I would appreciate if you can reply, thanks.

**Comment by adriangonz** [comment] 2023-03-16 09:13
Hey @ooooona ,

This is a duplicate of #952.

In particular, you can find the solution in https://github.com/SeldonIO/MLServer/issues/952#issuecomment-1383755218

We're aiming to clarify this on the docs as part of the next release.

**Closed by adriangonz** 2023-03-16 09:13 UTC

**Comment by ooooona** [comment] 2023-03-16 12:35
hi @adriangonz ,
thanks for your reply, I will try the solution~
